# Generated by Django 5.2.3 on 2026-02-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_maker', '0003_customer_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='org_name',
            field=models.CharField(max_length=255, verbose_name='Наименование организации / ФИО'),
        ),
    ]
