# Generated by Django 5.2.3 on 2025-06-23 19:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название проекта')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название проекта')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание проекта')),
                ('description_en', models.TextField(null=True, verbose_name='Описание проекта')),
                ('tech_stack', models.CharField(max_length=255, verbose_name='Используемые технологии')),
                ('repo_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на репозиторий')),
                ('demo_link_ru', models.URLField(blank=True, null=True, verbose_name='Ссылка на демо (ru)')),
                ('demo_link_en', models.URLField(blank=True, null=True, verbose_name='Ссылка на демо (en)')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsefulSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название софта')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название софта')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название софта')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('download_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на скачивание')),
                ('english_link', models.URLField(blank=True, null=True, verbose_name='English version link')),
                ('download_link_backup', models.URLField(blank=True, null=True, verbose_name='Резервная ссылка (RU)')),
                ('english_link_backup', models.URLField(blank=True, null=True, verbose_name='Резервная ссылка (EN)')),
                ('author', models.CharField(default='Liubov Kovaleva @LiuBA29', max_length=200, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
    ]
