# Generated by Django 5.1.4 on 2025-03-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('tech_stack', models.CharField(max_length=255, verbose_name='Используемые технологии')),
                ('repo_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на репозиторий')),
                ('demo_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на демо')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsefulSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название софта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('download_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на скачивание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
