# Generated by Django 5.2.3 on 2025-07-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usefulsoftware',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
