# Generated by Django 5.2.3 on 2025-11-14 17:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project_updated_at_usefulsoftware_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название софта')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название софта')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название софта')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('download_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на скачивание')),
                ('english_link', models.URLField(blank=True, null=True, verbose_name='English version link')),
                ('download_link_backup', models.URLField(blank=True, null=True, verbose_name='Резервная ссылка (RU)')),
                ('english_link_backup', models.URLField(blank=True, null=True, verbose_name='Резервная ссылка (EN)')),
                ('author', models.CharField(default='Liubov Kovaleva @LiuBA29', max_length=200, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'verbose_name': 'Софт для бизнеса',
                'verbose_name_plural': 'Софт для бизнеса',
            },
        ),
        migrations.RenameModel(
            old_name='UsefulSoftware',
            new_name='FreeSoftware',
        ),
        migrations.AlterModelOptions(
            name='freesoftware',
            options={'verbose_name': 'Бесплатный софт', 'verbose_name_plural': 'Бесплатный софт'},
        ),
    ]
