# Generated by Django 5.1.4 on 2025-04-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_contactmessage_name_en_contactmessage_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulsoftware',
            name='download_link',
            field=models.FileField(blank=True, null=True, upload_to='downloads/', verbose_name='Файл для скачивания'),
        ),
    ]
