# Generated by Django 5.1.4 on 2025-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_usefulsoftware_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulsoftware',
            name='download_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на скачивание'),
        ),
    ]
