# Generated by Django 5.2.3 on 2025-11-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_businesssoftware_rename_usefulsoftware_freesoftware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssoftware',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube видео (ссылка)'),
        ),
    ]
