# Generated by Django 5.1.4 on 2025-04-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_usefulsoftware_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefulsoftware',
            name='author',
            field=models.CharField(default='Liubov Kovaleva @LiuBA29', max_length=200, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='usefulsoftware',
            name='english_link',
            field=models.URLField(blank=True, null=True, verbose_name='English version link'),
        ),
    ]
