# Generated by Django 5.1.4 on 2025-04-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_usefulsoftware_author_usefulsoftware_english_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefulsoftware',
            name='download_link_backup',
            field=models.URLField(blank=True, null=True, verbose_name='Резервная ссылка (RU)'),
        ),
        migrations.AddField(
            model_name='usefulsoftware',
            name='english_link_backup',
            field=models.URLField(blank=True, null=True, verbose_name='Резервная ссылка (EN)'),
        ),
    ]
