# Generated by Django 5.2.3 on 2025-12-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP адрес клиента (для защиты от спама)', null=True, verbose_name='IP адрес'),
        ),
    ]
