# Generated by Django 5.1.4 on 2025-04-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_usefulsoftware_download_link_backup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo_link',
            new_name='demo_link_en',
        ),
        migrations.AddField(
            model_name='project',
            name='demo_link_ru',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на демо'),
        ),
    ]
