# Generated by Django 5.2.3 on 2025-12-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_order_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssoftware',
            name='demo_link',
            field=models.URLField(blank=True, help_text='Ссылка на бесплатную демо версию', null=True, verbose_name='Ссылка на демо версию'),
        ),
        migrations.AddField(
            model_name='businesssoftware',
            name='show_pricing',
            field=models.BooleanField(default=False, help_text='Включить отображение блока с тарифами (демо/стандарт/кастом)', verbose_name='Показывать блок тарифов'),
        ),
        migrations.AddField(
            model_name='businesssoftware',
            name='standard_price',
            field=models.CharField(blank=True, help_text="Например: '10000 руб' или 'от 5000 руб'", max_length=100, null=True, verbose_name='Цена стандартной версии'),
        ),
    ]
