# Generated by Django 5.1.4 on 2025-05-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_demo_link_project_demo_link_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_link_en',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на демо (en)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_link_ru',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на демо (ru)'),
        ),
    ]
