# Generated by Django 5.2.3 on 2025-12-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_order_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssoftware',
            name='standard_price',
            field=models.CharField(blank=True, help_text="Например: '10000' или 'от 5000' (BYN будет добавлен автоматически)", max_length=100, null=True, verbose_name='Цена стандартной версии'),
        ),
    ]
