# Generated by Django 5.1.4 on 2025-05-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_pageview_alter_project_demo_link_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageview',
            old_name='view_count',
            new_name='views_count',
        ),
        migrations.AlterField(
            model_name='pageview',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
