# Generated by Django 5.2.3 on 2026-01-12 18:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_businesssoftware_standard_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssoftware',
            name='instruction_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Загрузите PDF файл с инструкцией', max_length=255, null=True, verbose_name='Инструкция в PDF'),
        ),
        migrations.AddField(
            model_name='freesoftware',
            name='instruction_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Загрузите PDF файл с инструкцией', max_length=255, null=True, verbose_name='Инструкция в PDF'),
        ),
    ]
