# Generated by Django 5.2.3 on 2026-01-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_businesssoftware_instruction_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('file_name', models.CharField(max_length=200, verbose_name='Название файла')),
                ('file_type', models.CharField(help_text='pdf_instruction, installer_ru, installer_en, demo_ru, demo_en', max_length=50, verbose_name='Тип файла')),
                ('download_url', models.URLField(max_length=500, verbose_name='URL файла')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата скачивания')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('referer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Referer')),
                ('user_os', models.CharField(blank=True, max_length=50, null=True, verbose_name='ОС пользователя')),
            ],
            options={
                'verbose_name': 'Лог скачивания',
                'verbose_name_plural': 'Логи скачиваний',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='businesssoftware',
            name='instruction_pdf',
            field=models.CharField(blank=True, help_text='Введите прямую ссылку на PDF файл (например, из Cloudinary) или имя файла из директории assets/pdf (например: USER_GUIDE.pdf)', max_length=500, null=True, verbose_name='Ссылка на PDF инструкцию'),
        ),
        migrations.AlterField(
            model_name='freesoftware',
            name='instruction_pdf',
            field=models.CharField(blank=True, help_text='Введите прямую ссылку на PDF файл (например, из Cloudinary) или имя файла из директории assets/pdf (например: USER_GUIDE.pdf)', max_length=500, null=True, verbose_name='Ссылка на PDF инструкцию'),
        ),
    ]
