# Generated by Django 5.2.3 on 2026-01-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_downloadlog_alter_businesssoftware_instruction_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLinkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(help_text='youtube, repo, other', max_length=50, verbose_name='Тип ссылки')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('link_url', models.URLField(max_length=500, verbose_name='URL ссылки')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата перехода')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('referer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Referer')),
                ('user_os', models.CharField(blank=True, max_length=50, null=True, verbose_name='ОС пользователя')),
            ],
            options={
                'verbose_name': 'Лог внешних ссылок',
                'verbose_name_plural': 'Логи внешних ссылок',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
