# Generated by Django 5.2.3 on 2026-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_externallinklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssoftware',
            name='instruction_pdf_en',
            field=models.CharField(blank=True, help_text='Введите прямую ссылку на PDF файл (например, из Cloudinary) или имя файла из директории assets/pdf (например: USER_GUIDE_EN.pdf)', max_length=500, null=True, verbose_name='Ссылка на PDF инструкцию (EN)'),
        ),
    ]
