# Generated by Django 5.2.1 on 2025-06-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_guestuser_session_key_guestuser_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
