# Generated by Django 5.1.4 on 2025-03-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
