"""
Django settings for my_site project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
# import os.path
import os
from pathlib import Path
from dotenv import load_dotenv
import cloudinary

from django.utils.translation import gettext_lazy as _

# Загружаем переменные окружения

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

TURNSTILE_SITE_KEY = os.environ.get("TURNSTILE_SITE_KEY")




CSRF_TRUSTED_ORIGINS = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")


# Application definition

INSTALLED_APPS = [
    'channels',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'django.contrib.sitemaps',  # <-- добавь сюда
    'notes_app.apps.NotesAppConfig',
    'main_app.apps.MainAppConfig',
    'chat.apps.ChatConfig',
    'accounts.apps.AccountsConfig',
    'agregator.apps.AgregatorConfig',
    'contract_maker.apps.ContractMakerConfig',
    'bot.apps.BotConfig',

    'cloudinary',
    'cloudinary_storage',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main_app.middleware.PageViewMiddleware',
]

ROOT_URLCONF = 'my_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [BASE_DIR / "templates"],  # Директория для общих шаблонов
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',  # обязательно!
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main_app.context_processors.seo_keywords',  # SEO ключевые слова из проектов
                #'asterisk_app.context_processors.asterisk_connection_status',
            ],
        },
    },
]
WSGI_APPLICATION = 'my_site.wsgi.application'
ASGI_APPLICATION = 'my_site.asgi.application'

import  socket

REDIS_HOST = os.getenv('REDIS_HOST', 'redis')


if REDIS_HOST == 'redis':
    try:
        socket.gethostbyname('redis')
    except socket.gaierror:
        REDIS_HOST = '127.0.0.1'



CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, int(os.getenv('REDIS_PORT', 6379)))],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': BASE_DIR / os.getenv('DB_NAME', 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

gettext = lambda s: s
LANGUAGES = [
    ('ru', _('Russian')),
    ('en', _('English')),
]

MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'
MODELTRANSLATION_PREPOPULATE_LANGUAGE = 'en'

MODELTRANSLATION_TRANSLATION_FILES = (
    'notes_app.translation',
)


LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

LANGUAGE_CODE = 'ru'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'


# Папка, где будут храниться статические файлы на сервере (например, при сборке)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Папка 'static' в корне проекта
]

# Папка для сбора статических файлов при деплое
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')# Будет использоваться при запуске


# collectstatic
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-



MEDIA_URL = 'https://res.cloudinary.com/dczzlelzw/'
MEDIA_ROOT = BASE_DIR / 'media'  # Это можно оставить как есть для локальных файлов



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
    # Настройки для поддержки raw файлов (PDF, документы)
    'API_ENVIRONMENT_VARIABLE': None,
    'API_PROXY': None,
    'SECURE': True,
    'MEDIA_TAG': 'media',
    'INVALID_IMAGE_TAG': 'invalid',
    'STATIC_IMAGES_EXTENSIONS': ['jpg', 'jpe', 'jpeg', 'jpc', 'jp2', 'j2k', 'wdp', 'jxr', 'hdp', 'png', 'gif', 'webp', 'bmp', 'tif', 'tiff', 'ico'],
    'STATIC_VIDEOS_EXTENSIONS': ['mp4', 'webm', 'ogv'],
    'STATIC_RAW_EXTENSIONS': ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'rar'],
}

cloudinary.config(
    cloud_name=CLOUDINARY_STORAGE['CLOUD_NAME'],
    api_key=CLOUDINARY_STORAGE['API_KEY'],
    api_secret=CLOUDINARY_STORAGE['API_SECRET'],
    secure=CLOUDINARY_STORAGE.get('SECURE', True),
    # Увеличиваем таймауты для загрузки больших файлов
    timeout=600,  # 10 минут для загрузки больших PDF
)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Вспомогательный вывод для отладки (можно убрать в проде)
# print("Cloudinary API Key:", CLOUDINARY_STORAGE['API_KEY'])
AUTH_USER_MODEL = 'accounts.CustomUser'


TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')
# Бот @myregibot: кому отвечать (chat_id). Если не задано — используется TELEGRAM_CHAT_ID.
# Укажи свой user id в личке с ботом (узнать: @userinfobot), если уведомления уходят в группу (другой chat_id).
TELEGRAM_BOT_ALLOWED_CHAT_ID = os.getenv('TELEGRAM_BOT_ALLOWED_CHAT_ID')
TELEGRAM_BOT_ALLOWED_CHAT_IDS = os.getenv('TELEGRAM_BOT_ALLOWED_CHAT_IDS')

# Cloudflare Turnstile настройки
CLOUDFLARE_TURNSTILE_SITE_KEY = os.getenv('CLOUDFLARE_TURNSTILE_SITE_KEY', '')
CLOUDFLARE_TURNSTILE_SECRET_KEY = os.getenv('CLOUDFLARE_TURNSTILE_SECRET_KEY', '')

# Google Analytics
GOOGLE_ANALYTICS_ID = os.getenv('GOOGLE_ANALYTICS_ID', '')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Тест: токен для API добавления клиента из бота (опционально; если задан — проверяется в api_add_customer)
CONTRACT_MAKER_BOT_TOKEN = os.getenv('CONTRACT_MAKER_BOT_TOKEN', '')

# Настройки для загрузки больших файлов (PDF инструкции)
# Максимальный размер загружаемого файла: 100MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB в байтах
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB в байтах
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240  # Увеличиваем лимит полей формы
